import './globals.css'
import type { Metadata } from 'next'
import { Lexend_Deca, Big_Shoulders_Display } from 'next/font/google'

const Lexend_big = { subsets: ['Lexend_Deca', 'Big_Shoulders_Display'] }

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Lexend.className}>{children}</body>
    </html>
  )
}
